name: Deploy to Heroku

on:
  push:
    branches:
      - main  # You can adjust this to deploy on other branches as well.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js (or the appropriate environment for your app)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the appropriate Node.js version

      # Install dependencies (if it's a Node.js app)
      - name: Install dependencies
        run: npm install

      # Deploy to Heroku
      - name: Deploy to Heroku
        run: |
          git remote add heroku https://git.heroku.com/YOUR_APP_NAME.git
          git push heroku main
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Add your Heroku API key here as a secret
